-- ============================================================
-- DYNOBOO CHATBOT DATABASE SETUP (REVISED VERSION)
-- ============================================================

-- 1. Reset / Hapus Tabel Lama Jika Ingin Re-create dari Nol
DROP TABLE IF EXISTS chat_logs;
DROP TABLE IF EXISTS pesanan;
DROP TABLE IF EXISTS workshops;
DROP TABLE IF EXISTS knowledge_base;
DROP TABLE IF EXISTS settings;


-- ------------------------------------------------------------
-- 2. TABEL KNOWLEDGE BASE (Pengetahuan Bisnis + JSONB Opsi)
-- ------------------------------------------------------------
CREATE TABLE knowledge_base (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keywords TEXT NOT NULL,             -- Topik / Variasi Kata Kunci
    jawaban_utama TEXT NOT NULL,        -- Jawaban utama dari bot
    pilihan_jawaban JSONB,              -- Opsi cabang berbentuk array JSONB [{"opsi": "...", "jawaban": "..."}]
    keterangan TEXT,                    -- Catatan tambahan / konteks
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- ------------------------------------------------------------
-- 3. TABEL WORKSHOPS (Data Event Workshop Dinamis)
-- ------------------------------------------------------------
CREATE TABLE workshops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_workshop TEXT NOT NULL,
    tanggal TEXT NOT NULL,
    harga_promo TEXT,
    harga_normal TEXT,
    fasilitas TEXT,
    status TEXT DEFAULT 'ACTIVE',       -- 'ACTIVE', 'UPCOMING', atau 'CLOSED'
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- ------------------------------------------------------------
-- 4. TABEL PESANAN (Hasil Form Registrasi / Pemesanan DM)
-- ------------------------------------------------------------
CREATE TABLE pesanan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id TEXT NOT NULL,            -- ID Instagram User
    nama TEXT NOT NULL,                 -- Nama Lengkap
    alamat TEXT NOT NULL,               -- Alamat Pengiriman/Domisili
    no_hp TEXT NOT NULL,                -- Nomor HP / WhatsApp
    produk TEXT NOT NULL,               -- Produk / Workshop yang dipesan
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- ------------------------------------------------------------
-- 5. TABEL CHAT LOGS (Rekapan Log Percakapan Chatbot)
-- ------------------------------------------------------------
CREATE TABLE chat_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id TEXT NOT NULL,            -- ID Instagram User
    user_message TEXT NOT NULL,         -- Pesan dari user
    bot_response TEXT NOT NULL,         -- Balasan dari bot
    intent TEXT DEFAULT 'AI_GEMINI',    -- 'AI_GEMINI', 'FORM_REGISTRATION', 'START_REGISTRATION'
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- ============================================================
-- ROW LEVEL SECURITY (RLS) — izinkan anon key baca+tulis
-- ============================================================

ALTER TABLE knowledge_base ENABLE ROW LEVEL SECURITY;
ALTER TABLE workshops ENABLE ROW LEVEL SECURITY;
ALTER TABLE pesanan ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public all" ON knowledge_base FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all" ON workshops FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all" ON pesanan FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public all" ON chat_logs FOR ALL USING (true) WITH CHECK (true);


-- ============================================================
-- SEED DATA (INPUT DATA AWAL DARI EXCEL DYNOBOO)
-- ============================================================

-- A. Data Workshop Aktif
INSERT INTO workshops (nama_workshop, tanggal, harga_promo, harga_normal, fasilitas, status) VALUES
(
  'Penguin Beading Workshop',
  'Minggu, 5 Juli 2026 (Pukul 10:00 WIB)',
  'Rp60.000 (Khusus s.d. Minggu ini)',
  'Rp65.000 (Penutupan 4 Juli 2026 pukul 15.00 WIB)',
  'Bahan dan alat, tutor, konsumsi, dan e-certificate eksklusif dari DynoBoo',
  'ACTIVE'
);


-- B. Data QnA Knowledge Base
INSERT INTO knowledge_base (keywords, jawaban_utama, pilihan_jawaban, keterangan) VALUES
(
  'Mau nanya harga',
  'Halo, Kak! Kira-kira kakak mau nanya harga untuk barang/jasa apa ya?',
  '[
    {"opsi": "Produk", "jawaban": "Produk kita beragam yah harganya. Untuk menanyakan harga lebih detail mengenai produk spesifik, silakan tunggu jawaban langsung dari admin ya!"},
    {"opsi": "Workshop", "jawaban": "Workshop yang sedang berjalan saat ini adalah Penguin Beading workshop dengan harga Rp60k aja sampai hari minggu ini! Setelah itu harga akan naik ke Rp65k sampai tanggal penutupan di 4 Juli 2026 pukul 3 sore! Kamu udah bisa dapet bahan dan produk, tutor, konsumsi, hingga e-certificate eksklusif dari DynoBoo!"},
    {"opsi": "Kelas", "jawaban": "Kelas kita sedang dalam tahap pembuatan, admin akan kabarin kamu jika kelas kerajinan tangan sudah dibuka ya!!"}
  ]'::jsonb,
  '(tergantung dari workshop yang sedang berjalan)'
),
(
  'Info tentang workshop donk',
  'Untuk workshop kita dengan tema Penguin Beading workshop akan dimulai pada Minggu, 5 Juli 2026 dari pukul 10 pagi yah! Dengan harga pendaftaran yaitu 60k khusus hingga hari minggu ini, dan 65k setelahnya, kamu udah bakal dapet bahan dan alat, tutor, konsumsi, dan e-certificate dari DynoBoo yah!',
  NULL,
  '(tergantung dari workshop yang sedang berjalan)'
),
(
  'Private workshop',
  'DynoBoo ada sediain jasa workshop khusus untuk kamu dengan temen-temenmu sendiri! Jadi bisa sambil berkreasi dan bangun hubungan. Harga untuk setiap workshop private tergantung dari produk yang akan dibuat, tingkat kesulitan, jumlah pendaftar, dan urgensi di waktu yang dekat ya!',
  NULL,
  NULL
),
(
  'Ada produk khusus untuk wisuda gak?',
  'Ada banget! Kita punya bouquet edisi wisuda, naik kelas, sampai kelulusan sekolah. Tinggal pilih model bouquet yang kamu mau (dapat dilihat di highlight), dan kamu dapat memiliki bouquet yang bisa kamu abadikan sebagai pencapaian kamu!',
  '[
    {"opsi": "Berapaan harga bouquet wisudanya?", "jawaban": "Harga bouquet bunga wisuda kita start dari Rp40k sampai Rp45k yah~"},
    {"opsi": "Bisa request bunga gak?", "jawaban": "Maaf kak, untuk bunga sudah ditentukan yah. Namun untuk warna yang kakak mau masih bisa direquest yaah"}
  ]'::jsonb,
  NULL
),
(
  'Gimana cara ordernya?',
  'Untuk order, simpel aja kak! Kakak bisa langsung ketik "pesan" untuk mengisi form pendaftaran/pemesanan otomatis di sini, atau pesan via WhatsApp (0851-9591-6540) dengan format: Nama, Alamat, No. HP, dan Produk yang diinginkan.',
  NULL,
  NULL
),
(
  'Lokasi di mana / Kirim dari mana?',
  'Lokasi DynoBoo dan pengiriman kami ada di Kota Pontianak yah kak~ Pengiriman bisa menggunakan ojol (biaya ditanggung pembeli) atau kami antarkan langsung (gratis ongkir untuk jarak 2-4km dari lokasi kami)!',
  '[
    {"opsi": "Ojol", "jawaban": "Biaya pengiriman menggunakan ojol akan ditanggung oleh pembeli ya!"},
    {"opsi": "Diantarkan", "jawaban": "Pengiriman oleh kami gratis untuk dalam range 2-4km dari lokasi pengantaran, selebih dari itu pengiriman hanya kami terima menggunakan ojol ya!"}
  ]'::jsonb,
  NULL
),
(
  'Bayar lewat apa?',
  'Pembayaran bisa dilakukan dengan menggunakan transfer ke rekening BCA: 0293142481 (a.n. Franciska Angelica). Setelah itu, bukti transfer bisa dikirimkan lagi ke kami ya!',
  NULL,
  '(jika transaksi via online wajib transfer BCA)'
),
(
  'Bisa custom gak?',
  'Bisa banget! Kamu tinggal kirimin aja foto produk yang pengen DynoBoo buatkan ke kamu. Namun ingat yah, tidak semua produk dapat kami lakukan dikarenakan bahan yang kami punya terbatas ya! DynoMin bakal kabarin kamu lagi mengenai produk custom yang kamu mau yaah!',
  NULL,
  NULL
);
