-- ============================================================
-- JALANKAN DI SUPABASE SQL EDITOR
-- 003 - Admin Users + Audit Columns
-- ============================================================

-- 1. Tambah kolom edited_by ke knowledge_base
ALTER TABLE knowledge_base ADD COLUMN IF NOT EXISTS edited_by TEXT DEFAULT 'superadmin';
UPDATE knowledge_base SET edited_by = 'superadmin' WHERE edited_by IS NULL;

-- 2. Tambah kolom edited_by ke workshops
ALTER TABLE workshops ADD COLUMN IF NOT EXISTS edited_by TEXT DEFAULT 'superadmin';
UPDATE workshops SET edited_by = 'superadmin' WHERE edited_by IS NULL;

-- 3. Buat tabel admin_users
CREATE TABLE IF NOT EXISTS admin_users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,       -- SHA-256 hex hash
    role        TEXT NOT NULL DEFAULT 'admin',  -- 'superadmin' | 'admin'
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION handle_admin_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_admin_updated_at ON admin_users;
CREATE TRIGGER set_admin_updated_at
    BEFORE UPDATE ON admin_users
    FOR EACH ROW EXECUTE FUNCTION handle_admin_updated_at();

-- 4. RLS untuk admin_users
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public all" ON admin_users FOR ALL USING (true) WITH CHECK (true);

-- 5. PENTING: Setelah menjalankan SQL ini,
--    kunjungi http://localhost:3000/api/setup sekali
--    untuk membuat akun SuperAdmin pertama di database.
--    (Password: DynoBoo@2026)
